language: node_js
node_js:
  - "8"
services:
  - xvfb

before_script:
  - "export DISPLAY=:99.0"
  - "export SCREEN_WIDTH=1440"
  - "export SCREEN_HEIGHT=900"
  - "export SCREEN_DEPTH=24"
  - sh -e /etc/init.d/xvfb start
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24
  - sleep 3 # give xvfb some time to start
