language: node_js
node_js:
  - "8"
services:
  - xvfb

before_script:
  - "export DISPLAY=:99.0"
  - "export SCREEN_WIDTH=1440"
  - "export SCREEN_HEIGHT=900"
  - "export SCREEN_DEPTH=24"
  - sleep 3 # give xvfb some time to start
