language: node_js

node_js:
  - "8"

dist: trusty
services:
  - xvfb

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1440x900x24"

script:
  xvfb-run -s '-screen 0 1440x900x24' npm test;
